### ISSUE TITLE
디렉토리명 변경 (atom, utils, library)

### ISSUE THREAD

**Issue by 16EB** [42-transcendence/front-end#105]
지금 하려고 했는데, 그냥 했다가는 무수한 충돌을 경험할 것 같아서 되돌렸습니다.

1. atom -> atoms
2. utils -> libs
3. library -> 삭제 후 libs와 common으로 분류

## library 분류 계획
1. akasha-lib은 패키지로 추가 예정
2. 웹소켓 훅과 IDB는 libs에 이전
3. 서버-클라이언트 공용 파일인 generated와 payload는 구조를 변경하여 common으로 이전

**Comment by chanha-park** [comment]
https://github.com/42-transcendence/front-end/commit/7a2c3b08b0251a0ef0ffb906459953c11c00803c

이 이슈 닫아도 되나요 이제
