### ISSUE TITLE
채팅 마무리에 대한 에픽 퀘스트

### ISSUE THREAD

**Issue by 16EB** [42-transcendence/front-end#114]
- [x] 서버로부터 멤버 삽입/제거 패킷을 받으면 적절하게 처리하기 (ChatSocketProcessor)
- [x] 채팅 멤버 프로필을 UUID 대신 닉네임으로 표시하기 (useProfile 활용)
- [x] 멤버에 역할 표시해주기 (소유자, 관리자): 이름 오른쪽에 왕관?
- [x] 이미 채팅방에 포함된 친구는 초대 목록에서 제외시키기
- [x] 채팅 정지 목록 불러오고 관리하기
- [x] 라스트 메시지 문제: SyncCursor가 이상한 메시지에 대고 된다. ChatDialog의 useEffect 부분인데 훅 관계를 잘못 설계한듯
- [x] 채팅방에 입장했을 때 "마지막 메시지가 내가 보낸 메시지가 아니었더라도" 맨 밑으로 내려가져야함.
- [x] 채팅방 스크롤이 맨 밑에 있는 상태라면 "내가 보낸 메시지가 아니어도" 새로운 메시지가 왔을 때 따라서 내려가져야함.
- [x] 친구 눌러서 1:1 채팅방에 진입할 수 있어야 함. SetRoomUUID를 makeDirectChatKey로 만들어서 해주면 된다.
- [x] FzF 문제를 극복하기 위해서 useProfiles 같은 훅을 만들어서 프로필 리스트를 전부 갖추기 전까지 렌더링을 안하게 한다. (DM방 목록, 친구 목록, 초대 목록 등)
- [x] 공개방 찾기에서 이미 들어간 채팅방과 새로운 방을 구분한다. content를 활용하는 방안 생각중.
- [x] DM은 초대나 멤버, 방 옵션을 표시하지 않게 한다.
- [x] 정지된 유저가 채팅 치려고 할 때 기간 피드백. 입장에 있는 함수 복사-붙여넣기로 재활용할 수 있을듯 하다.
- [x] 공개방 찾기에서 새로고침이 필요함. 현재는 채팅 모달이 뜰때 최초에만 useEffect로 실행한다.
- [x] 방 정보 수정, 방 만들기 등 서버에서 에러 반환된 것을 받아서 핸들링 및 사용자에게 피드백
- [x] useProtected로 확인해서 친구가 아닌 상태의 유저는 초대할 수 없는 것으로 보이게 하기: 어차피 요청 보내도 서버가 막음
- [x] 프로필 훅의 더 디테일 버전 만들기. 오류가 발생했는지, 아직 로딩중인 것인지 등을 알 수 있도록.

**Comment by 16EB** [comment]
- [ ] 채팅 정지 목록 불러오고 관리하기
- [ ] 라스트 메시지 문제: SyncCursor가 이상한 메시지에 대고 된다. ChatDialog의 useEffect 부분인데 훅 관계를 잘못 설계한듯
- [ ] 채팅방에 입장했을 때 "마지막 메시지가 내가 보낸 메시지가 아니었더라도" 맨 밑으로 내려가져야함.
- [ ] 채팅방 스크롤이 맨 밑에 있는 상태라면 "내가 보낸 메시지가 아니어도" 새로운 메시지가 왔을 때 따라서 내려가져야함.
- [ ] 친구 눌러서 1:1 채팅방에 진입할 수 있어야 함. SetRoomUUID를 makeDirectChatKey로 만들어서 해주면 된다.
- [ ] FzF 문제를 극복하기 위해서 useProfiles 같은 훅을 만들어서 프로필 리스트를 전부 갖추기 전까지 렌더링을 안하게 한다. (DM방 목록, 친구 목록, 초대 목록 등)
- [ ] 공개방 찾기에서 이미 들어간 채팅방과 새로운 방을 구분한다. content를 활용하는 방안 생각중.
- [ ] 공개방 찾기에서 새로고침이 필요함. 현재는 채팅 모달이 뜰때 최초에만 useEffect로 실행한다.
- [ ] DM은 초대나 멤버, 방 옵션을 표시하지 않게 한다.
- [ ] 정지된 유저가 채팅 치려고 할 때 기간 피드백. 입장에 있는 함수 복사-붙여넣기로 재활용할 수 있을듯 하다.
- [ ] 방 정보 수정, 방 만들기 등 서버에서 에러 반환된 것을 받아서 핸들링 및 사용자에게 피드백

**Comment by chanha-park** [comment]
#34  이것도 관련 이슈

**Comment by chanha-park** [comment]
클로즈!
