### ISSUE TITLE
채팅방 마무리 2일차 에픽 퀘스트

### ISSUE THREAD

**Issue by 16EB** [42-transcendence/front-end#120]
엥? 이게 2일차가 되면 안되는데?

## 1
- [x] 친구 모달에서 신고가 나오는데 안나오게 해야함.
- [x] 채팅방의 관리자 임명 / 해임이 토글식으로 되어야 함.
- [x] 사용자 차단도 그렇게 토글형으로 되어야 함.
- [x] 기존 방 설정 메뉴를 [공개 / 비공개 전환], [비밀번호 설정]으로 분리한다. 이거도 가능하면 토글식으로 이름이 표시되면 좋을듯...
- [x] 비밀번호 설정은 쓸건지 먼저 confirm으로 물어보고 쓴다고 하면 prompt를 한다.
- [x] 친구 추가하기에서 프롬프트 두번 띄우지 말고 한번에서 #을 파싱하게 하기
- [x] 새로운 방 찾기에서 채팅방의 사진을 채팅방 UUID로 불러오게 하는데, 이렇게 하지 않게 하거나, 적절히 잘 구해오게 하기?
- [x] 채팅방의 사진들 조금 더 일관성 있게 띄우기. 차라리 1:1만 아바타 띄우고, 나머지는 전부 채팅방 UUID의 gravatar로 돌려버리는것도 나쁘지 않을듯.
- [x] 컨텍스트메뉴의 메뉴들 순서 / 호버 색깔 정리하기

## 2
- [x] 방 비밀번호를 매니저도 바꿀수있게
- [x] 방, 친구 목록 정렬하기
- [x] 내 상태 변경 온라인/자리비움/다른용무중/오프라인으로표시 4개 중에 하나 선택하게 해야함

## 3
- [x] 프로필 이미지 로더를 NEXT를 통하도록 하게 하기...? 현행은 임시 처리로 Avatar 참조
- [x] 프로필에서 OTP 설정 / 해제 (qrtest 디렉토리 참조)
- [x] 프로필에서 아바타 설정
- [x] FormData 보내고 있는거 useSWRMutation으로 바꿔주기

## 4
- [x] TODO/FIXME 정리하기
- [x] build가 가능하게 만들기

<< 여기까지는 진짜 오늘 안에 끝나야함...

## 5
- [x] 게임 레이아웃 (testy...) 이따가 저녁에 다 같이 모여서 하기

**Comment by chanha-park** [comment]
수고하셨습니다
