### ISSUE TITLE
image object-fit warning

### ISSUE THREAD

**Issue by chanha-park** [42-transcendence/front-end#2]
next/image 13버전에서 생기는 문제.

figma에서 export한 코드가 layout:fill을 쓰는데 거기서부터 생기는 문제인듯...?

https://nextjs.org/docs/messages/next-image-upgrade-to-13
https://stackoverflow.com/questions/65169431/how-to-set-the-next-image-component-to-100-height

**Comment by hdoo42** [comment]
꼼꼼하게 봐주셔서 감사합니다. object fit 쓰는 코드는 1404be4 커밋에서 제거했습니다.
