### ISSUE TITLE
게임 파트 UI

### ISSUE THREAD

**Issue by nimo-my** [42-transcendence/front-end#20]
### before game
- [x] 채팅
- [x] 캐릭터 선택창
- [x] 게임스타트 창
- [x] 게임 상단바

### after game
- [x] GameUserProfile
- [x] Round
- [x] GameUserFrame

### notations
- [x] CupNotation(trophy)
- [x] GoBackToGame
- [x] GameAchievements

## 🕹️게임 스크린(화면) 만들기
- [x] 게임 메인 화면 (방 만들 수 있는 화면!)
- [x] 게임 전 화면(대기화면)
- [x] 게임 화면(캔버스)
- [x] 게임 후 화면(대기 후 화면)

## 🕹️게임 화면 전환
- [x] 게임 화면 전환 (라우팅)

**Comment by nimo-my** [comment]
`jisookim-game` 브랜치에 올려놨습니다! 게임화면 UI 도 @main/game 안에다가 만들어볼게요!

**Comment by chanha-park** [comment]
이것도 기능상으론 다 했었으니 close합니다 나중에 고칠 때 reopen하거나 새 issue로...
