### ISSUE TITLE
이미지 파일들 이름 정리

### ISSUE THREAD

**Issue by chanha-park** [42-transcendence/front-end#29]
빈 아이콘 / 채워진 아이콘 이렇게 되어있는 경우가 많은데요,
지금은 이름이 통일되어있지 않아서...나중에 한번 바꾸는게 어떨까 합니다. 언젠가언젠가언젠가,,,
blankStar / filledStar
emptyCrown / filledCrown
chat / chatfilled
같은 식으로 되어있더라고요

얘네 자체 바꾸는건 별거 아닌데 그럼 얘네 import하는 파일들도 바꿔야하니 일단일단 이슈로만 올립니다

icon 사이트들 보면 보통 outlined/filled로 구분하는 것 같네요. [사이트1](https://icons8.com/icons) [사이트2](https://www.flaticon.com/icons)
겸사겸사 스네이크, 카멜케이스같은것도...

**Comment by 16EB** [comment]
#51 에서 해결하고 있습니다. 승인되면 close하겠습니다.

**Comment by 16EB** [comment]
GG
