### ISSUE TITLE
OTP 구현에 사용할 훅을 useReduce로 사용하기

### ISSUE THREAD

**Issue by 16EB** [42-transcendence/front-end#55]
호두님 찬파님 구현 모두 살펴보았는데요. 둘 다 state를 여러개 만들기 혹은 state에 배열을 담는 것, 마지막 입력 이벤트로 인한 변경을 특수하게 처리하는 특성으로 미루어 보았을 때, useReduce를 적용할 수 있어 보입니다. 나중에 시간나면 한번 시도해보죠.

**Comment by 16EB** [comment]
#16 이슈와 연관 있음.

**Comment by hdoo42** [comment]
useReducer 말씀이시죠? 저번에 햇갈려서 잘못 말했는데, zustand가 이 useReducer대신 쓴다고 소개해준 친구였어요. useContext대체재는 tan stack이라는 엄청 큰 오픈소스 웹개발 패키지가 있더라구요. 현업에서 많이 쓸정도로 기존 react hook들에 비해 많은 기능을 대신 해준다고 하니 한번 봐 볼 가치는 있을거같아요.

**Comment by 16EB** [comment]
**TanStack** 기억하겠습니다.

**Comment by chanha-park** [comment]
#90 풀리퀘에서 해당하는 부분을 다뤘는데요. 추후 useReducer 등을 쓰는 쪽으로 추가로 리팩토링을 해야할까요? 아니면 해결된 것으로 하고 close할까요?

**Comment by 16EB** [comment]
Reducer를 사용하지 않고 종결
