### ISSUE TITLE
NavBar 프렌드 모달 장착하기 

### ISSUE THREAD

**Issue by hdoo42** [42-transcendence/front-end#60]
프렌드 모달 띄우고 닫기 버튼을 이제 슬슬 네비게이션 바에 넣고싶네요. 

근데 이거에 적절한 아이콘이 뭘지 지금 고민중인데 잘 모르겠어요. .ㅜ

**Comment by chanha-park** [comment]
제 머리론 채팅이든 친구목록이든 말풍선 아이콘 / 사람한명 아이콘 / 사람여러명 있는 아이콘 정도 후보들밖에 안떠오르는데.... 정 안된다싶으면 큰 화면에서는 아이콘인지 이름이랑 같이 띄어주고, 화면 작아지면 글자만 사라지는 형식은 어떤가요? 추가로 수고가 들어가긴 하지만요.

**Comment by chanha-park** [comment]
일단 달았으니 닫겠습니다?
https://github.com/42-transcendence/front-end/commits/7a2c3b08b0251a0ef0ffb906459953c11c00803c/front/components/NavigationBar/FriendButton.tsx?browsing_rename_history=true&new_path=front/app/__libs__/components/NavigationBar/FriendButton.tsx&original_branch=main
