### ISSUE TITLE
welcome? setup 페이지 만들기

### ISSUE THREAD

**Issue by chanha-park** [42-transcendence/front-end#70]
# UI 셋업 (최초 로그인 이후 프로세스)

## 🦔 UI
- [x] UI Frame 컴포넌트로 제작 -> 계속 이용!
- [x] 피그마 제작
## 🦔 닉네임
- [x] 닉네임 UI
- [x] 닉네임(처음에 null, 이대로는 서비스 사용불가, 지정해야함)
## 🦔 프로필
- [x] 프로필 UI
- [x] 프로필 사진 설정 [테일윈드 사이트 참고](https://tailwindcss.com/docs/scroll-snap-stop) // [scroll event mdn](https://developer.mozilla.org/en-US/docs/Web/API/Document/scroll_event)   // [swiper 라이브러리](https://swiperjs.com/)
## 🦔 메인 페이지
- [x] 메인 페이지 UI
- [x] 메인 페이지 라우팅 quick match
- [x] 메인 페이지 라우팅 create game

**Comment by nimo-my** [comment]
**branch : `setup_page`**
- 피그마 제작 했습니다!
- `@main/welcome` 폴더 안에 `확인` 버튼을 만들었는데 자꾸 어디론가 이동하더라고요.. 아무것도 링크된 게 없는데 왜 이러는지 잘 모르겠습니다...
- `@main/welcome` 폴더에 닉네임과 관련되서 서버에서 닉네임이 중복되었는지, 가능한 닉네임인지 확인해야해요! 추후에 만들어야 함!
- `UIFrame` 을 자주 사용할 것 같아서 `components/UIFrame` 폴더 안에 파일 하나 만들었습니다.

**Comment by chanha-park** [comment]
>     * `@main/welcome` 폴더 안에 `확인` 버튼을 만들었는데 자꾸 어디론가 이동하더라고요.. 아무것도 링크된 게 없는데 왜 이러는지 잘 모르겠습니다...

답변이 늦었네요 ㅜ 이미 알아내셨을 수도 있지만...
button element는 type attribute를 가지는데요, 이는 버튼을 누르면 어떻게 동작하는지 지정합니다.
submit(default값, form을 서버에 제출함) / reset (말그대로 리셋...) / button (미지정, 기본적으로 아무것도 안하게 하고, javascript등으로 지정함) 세 가지가 가능합니다. 아마 아무것도 지정안해서 submit버튼이 되어 그런거 아닐까 합니다. 일단 `<button type="button">`으로 해두면 얌전해질겁니다. [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button)
그나저나 TextField인자로 button을 넣는거면 props이름으로 icon보단 그냥 button이 더 나을지도 모르겠네요

**Comment by nimo-my** [comment]
프로필 고르는건 `main/welcome2` 페이지에 만들어 놨습니다! 그런데 스크롤할때 스크롤 이벤트로 어떤 캐릭터 셀렉했는지 알려주는 함수 만들어야 해요! 제이맹님은 이벤트 리스너를 사용하거나 라이브러리를 사용하는 것을 권장하셨어요. 링크는 위에다가 수정해서 달아놨습니다!

**Comment by chanha-park** [comment]
가로스크롤 이렇게 보니 멋있네요.
[intersection observer](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) 쓰는건 어떤가요?
그런데 저희 프로필 사진 업로드하는걸로 생각했는데 기본 제공으로 가나요? 아니면 5개 기본제공에 마지막에 한칸 더 추가해서 + 아이콘같은거 그려놓고 파일선택 가능하게...?

**Comment by 16EB** [comment]
클래스 이름은 UI인데 파일 이름이 Ui네요. 이거도 가능하면 수정해주세요.

**Comment by nimo-my** [comment]
@chanha-park 본인 이미지 추가하거나 파일 업로드 할까 했는데 생각해니 그럼 저희 게임에서 게임말을 활용하기 어려울 것 같아서.. 그냥 캐릭터로만 하는게 좋을 것 같기도 하구요..!?
