### ISSUE TITLE
git branch  이름 컨벤션 통일하기

### ISSUE THREAD

**Issue by chanha-park** [42-transcendence/front-end#73]
막 develop release feature 이런것까지 구분은 아니더라도 최소한 카멜인지 스네이크인지 케밥인지 정도는 맞추는게 어떨까 합니다. 조금 더 세부적으로 정해도 좋고요.

nextjs는 이런식으로 쓰는군요
https://github.com/vercel/next.js/branches

**Comment by nimo-my** [comment]
저는 케밥이 좋아요~

**Comment by nimo-my** [comment]
**`케밥 케이스`로 하기로 했습니다!!!**
